### ISSUE TITLE
Points of Interest [Garages]

### ISSUE THREAD

**Issue by aethyriion** [digitrp/fivem-public-board#2]

**Comment by ThumblessCovert** [comment]
![20191207214856_1](https://user-images.githubusercontent.com/58632963/70383895-7088cd80-193b-11ea-8ffe-7935e3fcb2fd.jpg)

Legion

**Comment by ThumblessCovert** [comment]
![20191210110455_1](https://user-images.githubusercontent.com/58632963/70551312-e7d97f80-1b3c-11ea-83e8-a51c9b4b6f52.jpg)

possible garage point by lsia

**Comment by ThumblessCovert** [comment]
![20191210110525_1](https://user-images.githubusercontent.com/58632963/70551340-f9bb2280-1b3c-11ea-9fe9-52df192e380e.jpg)

other possible garage by lsia

**Comment by ThumblessCovert** [comment]
![20191210111223_1](https://user-images.githubusercontent.com/58632963/70551854-f5dbd000-1b3d-11ea-88cc-382d379741c4.jpg)

Other possible garage

**Comment by ThumblessCovert** [comment]
![20191210111933_1](https://user-images.githubusercontent.com/58632963/70552532-2a03c080-1b3f-11ea-8f5d-ea43c16d5d60.jpg)

helicopter garage by docks

**Comment by ThumblessCovert** [comment]
![20191210112216_1](https://user-images.githubusercontent.com/58632963/70552625-5a4b5f00-1b3f-11ea-834e-e6572210bf34.jpg)

marina for boat spawns

**Comment by NerxaOG** [comment]
![garage vinewood](https://user-images.githubusercontent.com/58798881/70715644-b8e81880-1cb8-11ea-81e2-b398757140a4.png)

**Comment by NerxaOG** [comment]
DOCKS GARAGE

![docks garage](https://user-images.githubusercontent.com/58798881/70715694-d0270600-1cb8-11ea-99a5-09938faa7202.png)

**Comment by NerxaOG** [comment]
CYPRESS GARAGE IN ALLEY

![cypress garage](https://user-images.githubusercontent.com/58798881/70715726-dddc8b80-1cb8-11ea-8aaf-0dcc1e88e23d.png)

**Comment by NerxaOG** [comment]
CYPRESS GARAGE ON MAIN ROAD

![cypress garage 2](https://user-images.githubusercontent.com/58798881/70715762-ed5bd480-1cb8-11ea-8202-21de464fbb5e.png)

**Comment by NerxaOG** [comment]
AIRPORT 2 CAR GARAGE

![airport garage](https://user-images.githubusercontent.com/58798881/70715794-019fd180-1cb9-11ea-8160-832d8a3dec92.png)

**Comment by NerxaOG** [comment]
PRIVATE POOL THAT CAN ONLY BE ACCESSED FROM A HIDDEN DOOR THAT LEADS DOWN A HALLWAY.

![private pool party](https://user-images.githubusercontent.com/58798881/70716795-0bc2cf80-1cbb-11ea-8989-70414a30059c.png)

![private pool location](https://user-images.githubusercontent.com/58798881/70716803-0ebdc000-1cbb-11ea-9649-a904bb2d9d61.png)

**Comment by NerxaOG** [comment]
GARAGE NEAR SANDY SHORES

![Garage near Sandy](https://user-images.githubusercontent.com/58798881/70718064-84c32680-1cbd-11ea-8e72-0622241dc8bf.png)

**Comment by glitchygg** [comment]
![FiveM_GTAProcess_KT64qIg5sN](https://user-images.githubusercontent.com/58341703/70772488-afa38e00-1d42-11ea-91cf-20cbb13f2e16.jpg)

147.15 321.09 112.14 292.54

**Comment by glitchygg** [comment]
![FiveM_GTAProcess_84g44UVvke](https://user-images.githubusercontent.com/58341703/70772622-19239c80-1d43-11ea-931f-86ed4c6a7315.jpg)

1205.47 -3102.93 5.85 184.49

**Comment by glitchygg** [comment]
![FiveM_GTAProcess_QEQZeHPQQg](https://user-images.githubusercontent.com/58341703/70772752-7ddef700-1d43-11ea-8dab-7efff0273e1f.jpg)

952.97 -1854.19 31.23 268.47

**Comment by glitchygg** [comment]
![FiveM_GTAProcess_PcDSDwUBuB](https://user-images.githubusercontent.com/58341703/70772859-d1e9db80-1d43-11ea-848d-6f93bafffa46.jpg)

-442.75 -2167.11 10.32 184.93

**Comment by glitchygg** [comment]
![FiveM_GTAProcess_y0SKLJclOS](https://user-images.githubusercontent.com/58341703/70772969-0d84a580-1d44-11ea-83f9-7c1825317889.jpg)

257.89 2601.79 44.86 179.62

**Comment by glitchygg** [comment]
![FiveM_GTAProcess_Z8wQoAZFMc](https://user-images.githubusercontent.com/58341703/70773465-8afce580-1d45-11ea-8f18-2476dee4ff0f.jpg)

-81.96 6491.75 31.49 36.93

**Comment by aethyriion** [comment]
I've added all of these
