### ISSUE TITLE
Garage glitch

### ISSUE THREAD

**Issue by 77nights** [digitrp/fivem-public-board#30]
Duplicates my vehicles after i entered, exited and re-entered the garage quickly
![FiveM - digit RP 12_31_2019 1_34_11 PM](https://user-images.githubusercontent.com/58625412/71630735-b51e2680-2bd2-11ea-9545-01ee1cdd198c.png)

**Comment by aethyriion** [comment]
upon exiting and entering again at a slower pace, were the cars cleared?

**Comment by 77nights** [comment]
yes after i left and re-entered it cleared the extra cars

**Comment by aethyriion** [comment]
I'll close this for now, them being cleared after another exit/entry means that "backup" system is working which checks for extra cars in the area.
