### ISSUE TITLE
Some kind of Issue...?

### ISSUE THREAD

**Issue by iChunkk** [digitrp/fivem-public-board#31]
this has happened to me a whole bunch. everything stops rendering and such, i fall through the map, and i have to fly out and lose the money in my wallet..

**Comment by iChunkk** [comment]
[
![0_20200101140701_1](https://user-images.githubusercontent.com/58867835/71645057-2e377f80-2ca0-11ea-9528-845015968209.png)
](url)


![0_20200101140709_1](https://user-images.githubusercontent.com/58867835/71645059-32fc3380-2ca0-11ea-9ac9-be52b14e571d.png)

**Comment by iChunkk** [comment]
![0_20200101163628_1](https://user-images.githubusercontent.com/58867835/71646339-f25ae500-2cb4-11ea-8198-9662b0ecfdfa.png)
![0_20200101163638_1](https://user-images.githubusercontent.com/58867835/71646341-f424a880-2cb4-11ea-9560-47a868acd87e.png)

**Comment by iChunkk** [comment]
AND AGAIN....

**Comment by aethyriion** [comment]
We are aware of the issue. Are opening your map the same moment that you are getting onto the vehicle?

**Comment by iChunkk** [comment]
@Cyntaax hmm. cant exactly remember, but that may be something im doing.

**Comment by aethyriion** [comment]
Try awaiting until your ped is done playing the "vehicle enter" animation before opening the map for the time being. I'll change the functionality of this in the next patch.

**Comment by iChunkk** [comment]
@Cyntaax well after i relogged, bike isnt in my garage and the Insurance place states "cannot help you at this time"

**Comment by aethyriion** [comment]
> this has happened to me a whole bunch. everything stops rendering and such, i fall through the map, and i have to fly out and lose the money in my wallet..

The disappearing act was fixed with https://github.com/digitrp/fivem-server/commit/c9ee579397b6584ea7e89f02952d45b1e3bf1948
