### ISSUE TITLE
Motorcycles

### ISSUE THREAD

**Issue by iChunkk** [digitrp/fivem-public-board#32]
Issue #1: Cannot fuel motorcycles at gas stations, Cyntaxx was aware.

Issue #2: Cannot fix motorcycle whether im on it, next to it, all around it, standing, ducked, anything. No vehicle detected for it.

**Comment by ThumblessCovert** [comment]
i was able to refuel a motorcycle. you may have an issue with the model you chose. i was also able to repair this motorcycle. standing right over the handlebars

**Comment by iChunkk** [comment]
@ThumblessCovert it may just be my model then. me and Crowbar did 360s around it, then crouched, standing, all of it.

**Comment by iChunkk** [comment]
got my bike to refuel. that issue is hit or miss for me. but the fixing was still hard to find.

**Comment by iChunkk** [comment]
ISSUE FIXED FOR NOW. FOUND GLITCH TO DO IT. ISSUE CLOSED
