### ISSUE TITLE
Fuel consumption rate appears high

### ISSUE THREAD

**Issue by NerxaOG** [digitrp/fivem-public-board#4]

**Comment by NerxaOG** [comment]
Gas tanks when full will run out of gas in under 3 minutes and 37 seconds.

**Comment by aethyriion** [comment]
Thanks for bringing this to our attention, just for reference, here's how the fuel calculation works. We'll have to settle on a good fuel consumption rate

```lua
				if rpm > 0.9 then
					rpmfuel = fuel - rpm / 0.8
					Citizen.Wait(1000)
				elseif rpm > 0.8 then
					rpmfuel = fuel - rpm / 1.1
					Citizen.Wait(1500)
				elseif rpm > 0.7 then
					rpmfuel = fuel - rpm / 2.2
					Citizen.Wait(2000)
				elseif rpm > 0.6 then
					rpmfuel = fuel - rpm / 4.1
					Citizen.Wait(3000)
				elseif rpm > 0.5 then
					rpmfuel = fuel - rpm / 5.7
					Citizen.Wait(4000)
				elseif rpm > 0.4 then
					rpmfuel = fuel - rpm / 6.4
					Citizen.Wait(5000)
				elseif rpm > 0.3 then
					rpmfuel = fuel - rpm / 6.9
					Citizen.Wait(6000)
				elseif rpm > 0.2 then
					rpmfuel = fuel - rpm / 7.3
					Citizen.Wait(8000)
				else
					rpmfuel = fuel - rpm / 7.5
					Citizen.Wait(5000)
				end
```

**Comment by MixerM3** [comment]
Possible Efficiency

if rpm > 0.9 then
					rpmfuel = fuel - rpm / 0.7
					Citizen.Wait(1000)
				elseif rpm > 0.8 then
					rpmfuel = fuel - rpm / 1.0
					Citizen.Wait(1500)
				elseif rpm > 0.7 then
					rpmfuel = fuel - rpm / 1.9
					Citizen.Wait(2000)
				elseif rpm > 0.6 then
					rpmfuel = fuel - rpm / 3.4
					Citizen.Wait(3000)
				elseif rpm > 0.5 then
					rpmfuel = fuel - rpm / 4.6
					Citizen.Wait(4000)
				elseif rpm > 0.4 then
					rpmfuel = fuel - rpm / 5.9
					Citizen.Wait(5000)
				elseif rpm > 0.3 then
					rpmfuel = fuel - rpm / 6.7
					Citizen.Wait(6000)
				elseif rpm > 0.2 then
					rpmfuel = fuel - rpm / 7.4
					Citizen.Wait(8000)
				else
					rpmfuel = fuel - rpm / 7.5
					Citizen.Wait(5000)
				end

**Comment by MixerM3** [comment]
`if rpm > 0.9 then
					rpmfuel = fuel - rpm / 0.7
					Citizen.Wait(1000)
				elseif rpm > 0.8 then
					rpmfuel = fuel - rpm / 1.0
					Citizen.Wait(1500)
				elseif rpm > 0.7 then
					rpmfuel = fuel - rpm / 1.9
					Citizen.Wait(2000)
				elseif rpm > 0.6 then
					rpmfuel = fuel - rpm / 3.4
					Citizen.Wait(3000)
				elseif rpm > 0.5 then
					rpmfuel = fuel - rpm / 4.6
					Citizen.Wait(4000)
				elseif rpm > 0.4 then
					rpmfuel = fuel - rpm / 5.9
					Citizen.Wait(5000)
				elseif rpm > 0.3 then
					rpmfuel = fuel - rpm / 6.7
					Citizen.Wait(6000)
				elseif rpm > 0.2 then
					rpmfuel = fuel - rpm / 7.4
					Citizen.Wait(8000)
				else
					rpmfuel = fuel - rpm / 7.5
					Citizen.Wait(5000)
				end`

**Comment by MixerM3** [comment]
if rpm > 0.9 then
					rpmfuel = fuel - rpm / 1.4
					Citizen.Wait(1000)
				elseif rpm > 0.8 then
					rpmfuel = fuel - rpm / 2.1
					Citizen.Wait(1500)
				elseif rpm > 0.7 then
					rpmfuel = fuel - rpm / 2.9
					Citizen.Wait(2000)
				elseif rpm > 0.6 then
					rpmfuel = fuel - rpm / 3.3
					Citizen.Wait(3000)
				elseif rpm > 0.5 then
					rpmfuel = fuel - rpm / 4.7
					Citizen.Wait(4000)
				elseif rpm > 0.4 then
					rpmfuel = fuel - rpm / 5.9
					Citizen.Wait(5000)
				elseif rpm > 0.3 then
					rpmfuel = fuel - rpm / 6.8
					Citizen.Wait(6000)
				elseif rpm > 0.2 then
					rpmfuel = fuel - rpm / 7.3
					Citizen.Wait(8000)
				else
					rpmfuel = fuel - rpm / 7.4
					Citizen.Wait(5000)
				end

**Comment by MixerM3** [comment]
Edit #5

```lua
if rpm > 0.9 then
rpmfuel = fuel - rpm / 4.10
Citizen.Wait(1000)
elseif rpm > 0.8 then
rpmfuel = fuel - rpm / 4.97
Citizen.Wait(1500)
elseif rpm > 0.7 then
rpmfuel = fuel - rpm / 5.43
Citizen.Wait(2000)
elseif rpm > 0.6 then
rpmfuel = fuel - rpm / 5.89
Citizen.Wait(3000)
elseif rpm > 0.5 then
rpmfuel = fuel - rpm / 6.24
Citizen.Wait(4000)
elseif rpm > 0.4 then
rpmfuel = fuel - rpm / 6.72
Citizen.Wait(5000)
elseif rpm > 0.3 then
rpmfuel = fuel - rpm / 7.35
Citizen.Wait(6000)
elseif rpm > 0.2 then
rpmfuel = fuel - rpm / 7.61
Citizen.Wait(8000)
else
rpmfuel = fuel - rpm / 7.98
Citizen.Wait(5000)
end
```

**Comment by aethyriion** [comment]
@MixerM3 @glitchygg How are we feeling since these last changes?

**Comment by glitchygg** [comment]
Fuel seems good. Thank you @MixerM3

**Comment by MixerM3** [comment]
```lua
if rpm > 0.9 then
rpmfuel = fuel - rpm / 4.10
Citizen.Wait(1000)
elseif rpm > 0.8 then
rpmfuel = fuel - rpm / 4.97
Citizen.Wait(1500)
elseif rpm > 0.7 then
rpmfuel = fuel - rpm / 5.43
Citizen.Wait(2000)
elseif rpm > 0.6 then
rpmfuel = fuel - rpm / 5.89
Citizen.Wait(3000)
elseif rpm > 0.5 then
rpmfuel = fuel - rpm / 6.24
Citizen.Wait(4000)
elseif rpm > 0.4 then
rpmfuel = fuel - rpm / 6.72
Citizen.Wait(5000)
elseif rpm > 0.3 then
rpmfuel = fuel - rpm / 7.35
Citizen.Wait(6000)
elseif rpm > 0.2 then
rpmfuel = fuel - rpm / 7.61
Citizen.Wait(8000)
else
rpmfuel = fuel - rpm / 7.98
Citizen.Wait(5000)
end
```
